; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "InfoCO"
#define MyAppVersion "1.0.7"
#define MyAppPublisher "Lovepsone"
#define MyAppURL "http://forum.stalker-online.so/viewtopic.php?f=15&t=8209&lng=ru"
#define MyAppExeName "InfoCO.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{40EBE7C0-59A7-40BB-91AB-A71A1111D030}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=E:\Repazitoriy\InfoCO
OutputBaseFilename=setup
SetupIconFile=E:\Repazitoriy\InfoCO\InfoCO\infoco.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "E:\Repazitoriy\InfoCO\Win32\Release\InfoCO.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Repazitoriy\InfoCO\Win32\Release\InfoCOData.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Repazitoriy\InfoCO\Win32\Release\QtCore4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Repazitoriy\InfoCO\Win32\Release\QtGui4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Repazitoriy\InfoCO\Win32\Release\QtXml4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Repazitoriy\InfoCO\Win32\Release\COPYING"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Repazitoriy\InfoCO\Win32\Release\images\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don{61BDE96F-3F51-43AC-AE8D-5A02DBC8BD8B}'t use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

